version: '3.8'
services:
  database-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=DBBookingCare
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - '3307:3306'
    expose:
      - 3306

  backend:
    build:
      context: ../BackEnd
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=database-mysql
      - URL_REACT=http://localhost
      # - DB_HOST=host.docker.internal
    ports:
      - 8080:8080
    expose:
      - 8080

  nginx:
    image: nginx:1.23.3
    ports:
      - 80:80
    volumes:
      - ../FrontEnd/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

# docker compose -p hoidanit-sern up -d
